#! /usr/bin/env bash

TMP_WORKTREE="$(mktemp -d)/"

git checkout-index --prefix="${TMP_WORKTREE}" --all

ext_or_shebang() {
    local FILE="$1"
    local EXT="$2"
    local SHEBANG="$3"

    if [[ "$FILE" = *".${EXT}" ]]; then
        printf "%s\0" "$FILE"
    else
        read -r -n 2 MAGIC < "$FILE"
        if [[ "$MAGIC" = "#!" ]] && head -n1 "$FILE" | grep -q "$SHEBANG"; then
            printf "%s\0" "$FILE"
        fi
    fi
}

run_on_files_with_ext() {
    local EXT="$1"
    local SHEBANG="$2"
    shift 2
    git diff-index --cached --name-only --diff-filter=ACMR -z HEAD \
        | sed -zn "s#^#${TMP_WORKTREE}# p" \
        | while read -r -d $'\0' FILE; do ext_or_shebang "$FILE" "$EXT" "$SHEBANG"; done \
        | xargs -r0 "$@"
}

max() {
    if [ "$1" -gt "$2" ]; then
        echo "$1"
    else
        echo "$2"
    fi
}

declare -i RET=0

if command -v flake8 > /dev/null; then
    run_on_files_with_ext py python flake8 --ignore=E501,W503
    RET=$?
elif command -v pep8 > /dev/null; then
    run_on_files_with_ext py python pep8 --ignore=E501,W503
    RET=$?
fi

if command -v php > /dev/null; then
    run_on_files_with_ext php php php -l
fi

if command -v shellcheck > /dev/null; then
    run_on_files_with_ext sh '\b\(bash\|sh\)' shellcheck -x
    RET="$(max "$RET" "$?")"
fi

rm -rf "$TMP_WORKTREE"

exit "$RET"
